# Generated by Django 5.2 on 2025-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0002_alter_link_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(),
        ),
    ]
